# Site Settings
baseurl: ""
url : "https://keongmini.github.io"

# Blog Settings
theme_settings :
  title : Grape Theme
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/bg.JPG
    username : Keongmini
    description : I am a software developer!
    experience :
      - start : 2020-01-01
        end : 0000-00-00
        experience : company name, title
    skills : 
      - skill : JavaScript & Python
        value : 75  # Percent value
        
  # Icons
  icons :
    email: kmnam09@gmail.com
    # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: keongmini
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
